name: pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: main
          submodules: recursive
      - name: setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.69.0'
          extended: true
      - name: build
        run: |
          hugo --verbose --gc --minify
          ls -la public
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
